# -*- coding: utf-8
from emoji import emojize
notebook_with_decorative_cover = emojize(":notebook with decorative cover:")
closed_book = emojize(":closed book:")
open_book = emojize(":open book:")
green_book = emojize(":green book:")
blue_book = emojize(":blue book:")
orange_book = emojize(":orange book:")
books = emojize(":books:")
notebook = emojize(":notebook:")
ledger = emojize(":ledger:")
page_with_curl = emojize(":page with curl:")
scroll = emojize(":scroll:")
page_facing_up = emojize(":page facing up:")
newspaper = emojize(":newspaper:")
rolled_up_newspaper = emojize(":rolled-up newspaper:")
bookmark_tabs = emojize(":bookmark tabs:")
bookmark = emojize(":bookmark:")
label = emojize(":label:")
