# -*- coding: utf-8
from emoji import emojize
battery = emojize(":battery:")
low_battery = emojize(":low battery:")
electric_plug = emojize(":electric plug:")
laptop = emojize(":laptop:")
desktop_computer = emojize(":desktop computer:")
printer = emojize(":printer:")
keyboard = emojize(":keyboard:")
computer_mouse = emojize(":computer mouse:")
trackball = emojize(":trackball:")
computer_disk = emojize(":computer disk:")
floppy_disk = emojize(":floppy disk:")
optical_disk = emojize(":optical disk:")
dvd = emojize(":dvd:")
abacus = emojize(":abacus:")
