# -*- coding: utf-8
from emoji import emojize
door = emojize(":door:")
elevator = emojize(":elevator:")
mirror = emojize(":mirror:")
window = emojize(":window:")
bed = emojize(":bed:")
couch_and_lamp = emojize(":couch and lamp:")
chair = emojize(":chair:")
toilet = emojize(":toilet:")
plunger = emojize(":plunger:")
shower = emojize(":shower:")
bathtub = emojize(":bathtub:")
mouse_trap = emojize(":mouse trap:")
razor = emojize(":razor:")
lotion_bottle = emojize(":lotion bottle:")
safety_pin = emojize(":safety pin:")
broom = emojize(":broom:")
basket = emojize(":basket:")
roll_of_paper = emojize(":roll of paper:")
bucket = emojize(":bucket:")
soap = emojize(":soap:")
bubbles = emojize(":bubbles:")
toothbrush = emojize(":toothbrush:")
sponge = emojize(":sponge:")
fire_extinguisher = emojize(":fire extinguisher:")
shopping_cart = emojize(":shopping cart:")
