# -*- coding: utf-8
from emoji import emojize
movie_camera = emojize(":movie camera:")
film_frames = emojize(":film frames:")
film_projector = emojize(":film projector:")
clapper_board = emojize(":clapper board:")
television = emojize(":television:")
camera = emojize(":camera:")
camera_with_flash = emojize(":camera with flash:")
video_camera = emojize(":video camera:")
videocassette = emojize(":videocassette:")
magnifying_glass_tilted_left = emojize(":magnifying glass tilted left:")
magnifying_glass_tilted_right = emojize(":magnifying glass tilted right:")
candle = emojize(":candle:")
light_bulb = emojize(":light bulb:")
flashlight = emojize(":flashlight:")
red_paper_lantern = emojize(":red paper lantern:")
diya_lamp = emojize(":diya lamp:")
