# -*- coding: utf-8
from emoji import emojize
envelope = emojize(":envelope:")
e_mail = emojize(":e-mail:")
incoming_envelope = emojize(":incoming envelope:")
envelope_with_arrow = emojize(":envelope with arrow:")
outbox_tray = emojize(":outbox tray:")
inbox_tray = emojize(":inbox tray:")
package = emojize(":package:")
closed_mailbox_with_raised_flag = emojize(":closed mailbox with raised flag:")
closed_mailbox_with_lowered_flag = emojize(":closed mailbox with lowered flag:")
open_mailbox_with_raised_flag = emojize(":open mailbox with raised flag:")
open_mailbox_with_lowered_flag = emojize(":open mailbox with lowered flag:")
postbox = emojize(":postbox:")
ballot_box_with_ballot = emojize(":ballot box with ballot:")
