# -*- coding: utf-8
from emoji import emojize
briefcase = emojize(":briefcase:")
file_folder = emojize(":file folder:")
open_file_folder = emojize(":open file folder:")
card_index_dividers = emojize(":card index dividers:")
calendar = emojize(":calendar:")
tear_off_calendar = emojize(":tear-off calendar:")
spiral_notepad = emojize(":spiral notepad:")
spiral_calendar = emojize(":spiral calendar:")
card_index = emojize(":card index:")
chart_increasing = emojize(":chart increasing:")
chart_decreasing = emojize(":chart decreasing:")
bar_chart = emojize(":bar chart:")
clipboard = emojize(":clipboard:")
pushpin = emojize(":pushpin:")
round_pushpin = emojize(":round pushpin:")
paperclip = emojize(":paperclip:")
linked_paperclips = emojize(":linked paperclips:")
straight_ruler = emojize(":straight ruler:")
triangular_ruler = emojize(":triangular ruler:")
scissors = emojize(":scissors:")
card_file_box = emojize(":card file box:")
file_cabinet = emojize(":file cabinet:")
wastebasket = emojize(":wastebasket:")
