# -*- coding: utf-8
from emoji import emojize
hammer = emojize(":hammer:")
axe = emojize(":axe:")
pick = emojize(":pick:")
hammer_and_pick = emojize(":hammer_and_pick:")
hammer_and_wrench = emojize(":hammer_and_wrench:")
dagger = emojize(":dagger:")
crossed_swords = emojize(":crossed_swords:")
water_pistol = emojize(":water_pistol:")
boomerang = emojize(":boomerang:")
bow_and_arrow = emojize(":bow_and_arrow:")
shield = emojize(":shield:")
carpentry_saw = emojize(":carpentry_saw:")
wrench = emojize(":wrench:")
screwdriver = emojize(":screwdriver:")
nut_and_bolt = emojize(":nut_and_bolt:")
gear = emojize(":gear:")
clamp = emojize(":clamp:")
balance_scale = emojize(":balance_scale:")
white_cane = emojize(":white_cane:")
link = emojize(":link:")
chains = emojize(":chains:")
hook = emojize(":hook:")
toolbox = emojize(":toolbox:")
magnet = emojize(":magnet:")
ladder = emojize(":ladder:")
