# -*- coding: utf-8
from emoji import emojize
hammer = emojize(":hammer:")
axe = emojize(":axe:")
pick = emojize(":pick:")
hammer_and_pick = emojize(":hammer and pick:")
hammer_and_wrench = emojize(":hammer and wrench:")
dagger = emojize(":dagger:")
crossed_swords = emojize(":crossed swords:")
water_pistol = emojize(":water pistol:")
boomerang = emojize(":boomerang:")
bow_and_arrow = emojize(":bow and arrow:")
shield = emojize(":shield:")
carpentry_saw = emojize(":carpentry saw:")
wrench = emojize(":wrench:")
screwdriver = emojize(":screwdriver:")
nut_and_bolt = emojize(":nut and bolt:")
gear = emojize(":gear:")
clamp = emojize(":clamp:")
balance_scale = emojize(":balance scale:")
white_cane = emojize(":white cane:")
link = emojize(":link:")
chains = emojize(":chains:")
hook = emojize(":hook:")
toolbox = emojize(":toolbox:")
magnet = emojize(":magnet:")
ladder = emojize(":ladder:")
