# -*- coding: utf-8
from emoji import emojize
up_arrow = emojize(":up_arrow:")
up_right_arrow = emojize(":up_right_arrow:")
right_arrow = emojize(":right_arrow:")
down_right_arrow = emojize(":down_right_arrow:")
down_arrow = emojize(":down_arrow:")
down_left_arrow = emojize(":down_left_arrow:")
left_arrow = emojize(":left_arrow:")
up_left_arrow = emojize(":up_left_arrow:")
up_down_arrow = emojize(":up_down_arrow:")
left_right_arrow = emojize(":left_right_arrow:")
right_arrow_curving_left = emojize(":right_arrow_curving_left:")
left_arrow_curving_right = emojize(":left_arrow_curving_right:")
right_arrow_curving_up = emojize(":right_arrow_curving_up:")
right_arrow_curving_down = emojize(":right_arrow_curving_down:")
clockwise_vertical_arrows = emojize(":clockwise_vertical_arrows:")
counterclockwise_arrows_button = emojize(":counterclockwise_arrows_button:")
back_arrow = emojize(":back_arrow:")
end_arrow = emojize(":end_arrow:")
on_arrow = emojize(":on_arrow:")
soon_arrow = emojize(":soon_arrow:")
top_arrow = emojize(":top_arrow:")
