# -*- coding: utf-8
from emoji import emojize
up_arrow = emojize(":up arrow:")
up_right_arrow = emojize(":up-right arrow:")
right_arrow = emojize(":right arrow:")
down_right_arrow = emojize(":down-right arrow:")
down_arrow = emojize(":down arrow:")
down_left_arrow = emojize(":down-left arrow:")
left_arrow = emojize(":left arrow:")
up_left_arrow = emojize(":up-left arrow:")
up_down_arrow = emojize(":up-down arrow:")
left_right_arrow = emojize(":left-right arrow:")
right_arrow_curving_left = emojize(":right arrow curving left:")
left_arrow_curving_right = emojize(":left arrow curving right:")
right_arrow_curving_up = emojize(":right arrow curving up:")
right_arrow_curving_down = emojize(":right arrow curving down:")
clockwise_vertical_arrows = emojize(":clockwise vertical arrows:")
counterclockwise_arrows_button = emojize(":counterclockwise arrows button:")
back_arrow = emojize(":BACK arrow:")
end_arrow = emojize(":END arrow:")
on_arrow = emojize(":ON! arrow:")
soon_arrow = emojize(":SOON arrow:")
top_arrow = emojize(":TOP arrow:")
