# -*- coding: utf-8
from emoji import emojize
shuffle_tracks_button = emojize(":shuffle tracks button:")
repeat_button = emojize(":repeat button:")
repeat_single_button = emojize(":repeat single button:")
play_button = emojize(":play button:")
fast_forward_button = emojize(":fast-forward button:")
next_track_button = emojize(":next track button:")
play_or_pause_button = emojize(":play or pause button:")
reverse_button = emojize(":reverse button:")
fast_reverse_button = emojize(":fast reverse button:")
last_track_button = emojize(":last track button:")
upwards_button = emojize(":upwards button:")
fast_up_button = emojize(":fast up button:")
downwards_button = emojize(":downwards button:")
fast_down_button = emojize(":fast down button:")
pause_button = emojize(":pause button:")
stop_button = emojize(":stop button:")
record_button = emojize(":record button:")
eject_button = emojize(":eject button:")
cinema = emojize(":cinema:")
dim_button = emojize(":dim button:")
bright_button = emojize(":bright button:")
antenna_bars = emojize(":antenna bars:")
vibration_mode = emojize(":vibration mode:")
mobile_phone_off = emojize(":mobile phone off:")
