# -*- coding: utf-8
from emoji import emojize
medical_symbol = emojize(":medical symbol:")
recycling_symbol = emojize(":recycling symbol:")
fleur_de_lis = emojize(":fleur-de-lis:")
trident_emblem = emojize(":trident emblem:")
name_badge = emojize(":name badge:")
japanese_symbol_for_beginner = emojize(":Japanese symbol for beginner:")
hollow_red_circle = emojize(":hollow red circle:")
check_mark_button = emojize(":check mark button:")
check_box_with_check = emojize(":check box with check:")
check_mark = emojize(":check mark:")
cross_mark = emojize(":cross mark:")
cross_mark_button = emojize(":cross mark button:")
curly_loop = emojize(":curly loop:")
double_curly_loop = emojize(":double curly loop:")
part_alternation_mark = emojize(":part alternation mark:")
eight_spoked_asterisk = emojize(":eight-spoked asterisk:")
eight_pointed_star = emojize(":eight-pointed star:")
sparkle = emojize(":sparkle:")
copyright = emojize(":copyright:")
registered = emojize(":registered:")
trade_mark = emojize(":trade mark:")
