# -*- coding: utf-8
from emoji import emojize
atm_sign = emojize(":ATM sign:")
litter_in_bin_sign = emojize(":litter in bin sign:")
potable_water = emojize(":potable water:")
wheelchair_symbol = emojize(":wheelchair symbol:")
mens_room = emojize(":men’s room:")
womens_room = emojize(":women’s room:")
restroom = emojize(":restroom:")
baby_symbol = emojize(":baby symbol:")
water_closet = emojize(":water closet:")
passport_control = emojize(":passport control:")
customs = emojize(":customs:")
baggage_claim = emojize(":baggage claim:")
left_luggage = emojize(":left luggage:")
