# -*- coding: utf-8
from emoji import emojize
warning = emojize(":warning:")
children_crossing = emojize(":children crossing:")
no_entry = emojize(":no entry:")
prohibited = emojize(":prohibited:")
no_bicycles = emojize(":no bicycles:")
no_smoking = emojize(":no smoking:")
no_littering = emojize(":no littering:")
non_potable_water = emojize(":non-potable water:")
no_pedestrians = emojize(":no pedestrians:")
no_mobile_phones = emojize(":no mobile phones:")
no_one_under_eighteen = emojize(":no one under eighteen:")
radioactive = emojize(":radioactive:")
biohazard = emojize(":biohazard:")
