# -*- coding: utf-8
from emoji import emojize
aries = emojize(":Aries:")
taurus = emojize(":Taurus:")
gemini = emojize(":Gemini:")
cancer = emojize(":Cancer:")
leo = emojize(":Leo:")
virgo = emojize(":Virgo:")
libra = emojize(":Libra:")
scorpio = emojize(":Scorpio:")
sagittarius = emojize(":Sagittarius:")
capricorn = emojize(":Capricorn:")
aquarius = emojize(":Aquarius:")
pisces = emojize(":Pisces:")
ophiuchus = emojize(":Ophiuchus:")
