# -*- coding: utf-8
from emoji import emojize
aries = emojize(":aries:")
taurus = emojize(":taurus:")
gemini = emojize(":gemini:")
cancer = emojize(":cancer:")
leo = emojize(":leo:")
virgo = emojize(":virgo:")
libra = emojize(":libra:")
scorpio = emojize(":scorpio:")
sagittarius = emojize(":sagittarius:")
capricorn = emojize(":capricorn:")
aquarius = emojize(":aquarius:")
pisces = emojize(":pisces:")
ophiuchus = emojize(":ophiuchus:")
