# -*- coding: utf-8
from emoji import emojize
seedling = emojize(":seedling:")
potted_plant = emojize(":potted plant:")
evergreen_tree = emojize(":evergreen tree:")
deciduous_tree = emojize(":deciduous tree:")
palm_tree = emojize(":palm tree:")
cactus = emojize(":cactus:")
sheaf_of_rice = emojize(":sheaf of rice:")
herb = emojize(":herb:")
shamrock = emojize(":shamrock:")
four_leaf_clover = emojize(":four leaf clover:")
maple_leaf = emojize(":maple leaf:")
fallen_leaf = emojize(":fallen leaf:")
leaf_fluttering_in_wind = emojize(":leaf fluttering in wind:")
empty_nest = emojize(":empty nest:")
nest_with_eggs = emojize(":nest with eggs:")
