# -*- coding: utf-8
from emoji import emojize
notebook_with_decorative_cover = emojize(":notebook_with_decorative_cover:")
closed_book = emojize(":closed_book:")
open_book = emojize(":open_book:")
green_book = emojize(":green_book:")
blue_book = emojize(":blue_book:")
orange_book = emojize(":orange_book:")
books = emojize(":books:")
notebook = emojize(":notebook:")
ledger = emojize(":ledger:")
page_with_curl = emojize(":page_with_curl:")
scroll = emojize(":scroll:")
page_facing_up = emojize(":page_facing_up:")
newspaper = emojize(":newspaper:")
rolled_up_newspaper = emojize(":rolled-up_newspaper:")
bookmark_tabs = emojize(":bookmark_tabs:")
bookmark = emojize(":bookmark:")
label = emojize(":label:")
