# -*- coding: utf-8
from emoji import emojize
briefcase = emojize(":briefcase:")
file_folder = emojize(":file_folder:")
open_file_folder = emojize(":open_file_folder:")
card_index_dividers = emojize(":card_index_dividers:")
calendar = emojize(":calendar:")
tear_off_calendar = emojize(":tear-off_calendar:")
spiral_notepad = emojize(":spiral_notepad:")
spiral_calendar = emojize(":spiral_calendar:")
card_index = emojize(":card_index:")
chart_increasing = emojize(":chart_increasing:")
chart_decreasing = emojize(":chart_decreasing:")
bar_chart = emojize(":bar_chart:")
clipboard = emojize(":clipboard:")
pushpin = emojize(":pushpin:")
round_pushpin = emojize(":round_pushpin:")
paperclip = emojize(":paperclip:")
linked_paperclips = emojize(":linked_paperclips:")
straight_ruler = emojize(":straight_ruler:")
triangular_ruler = emojize(":triangular_ruler:")
scissors = emojize(":scissors:")
card_file_box = emojize(":card_file_box:")
file_cabinet = emojize(":file_cabinet:")
wastebasket = emojize(":wastebasket:")
