# -*- coding: utf-8
from emoji import emojize
turkey = emojize(":turkey:")
chicken = emojize(":chicken:")
rooster = emojize(":rooster:")
hatching_chick = emojize(":hatching_chick:")
baby_chick = emojize(":baby_chick:")
front_facing_baby_chick = emojize(":front-facing_baby_chick:")
bird = emojize(":bird:")
penguin = emojize(":penguin:")
dove = emojize(":dove:")
eagle = emojize(":eagle:")
duck = emojize(":duck:")
swan = emojize(":swan:")
owl = emojize(":owl:")
dodo = emojize(":dodo:")
feather = emojize(":feather:")
flamingo = emojize(":flamingo:")
peacock = emojize(":peacock:")
parrot = emojize(":parrot:")
