# -*- coding: utf-8
from emoji import emojize
snail = emojize(":snail:")
butterfly = emojize(":butterfly:")
bug = emojize(":bug:")
ant = emojize(":ant:")
honeybee = emojize(":honeybee:")
beetle = emojize(":beetle:")
lady_beetle = emojize(":lady_beetle:")
cricket = emojize(":cricket:")
cockroach = emojize(":cockroach:")
spider = emojize(":spider:")
spider_web = emojize(":spider_web:")
scorpion = emojize(":scorpion:")
mosquito = emojize(":mosquito:")
fly = emojize(":fly:")
worm = emojize(":worm:")
microbe = emojize(":microbe:")
