# -*- coding: utf-8
from emoji import emojize
jack_o_lantern = emojize(":jack-o-lantern:")
christmas_tree = emojize(":Christmas tree:")
fireworks = emojize(":fireworks:")
sparkler = emojize(":sparkler:")
firecracker = emojize(":firecracker:")
sparkles = emojize(":sparkles:")
balloon = emojize(":balloon:")
party_popper = emojize(":party popper:")
confetti_ball = emojize(":confetti ball:")
tanabata_tree = emojize(":tanabata tree:")
pine_decoration = emojize(":pine decoration:")
japanese_dolls = emojize(":Japanese dolls:")
carp_streamer = emojize(":carp streamer:")
wind_chime = emojize(":wind chime:")
moon_viewing_ceremony = emojize(":moon viewing ceremony:")
red_envelope = emojize(":red envelope:")
ribbon = emojize(":ribbon:")
wrapped_gift = emojize(":wrapped gift:")
reminder_ribbon = emojize(":reminder ribbon:")
admission_tickets = emojize(":admission tickets:")
ticket = emojize(":ticket:")
