# -*- coding: utf-8
from emoji import emojize
jack_o_lantern = emojize(":jack_o_lantern:")
christmas_tree = emojize(":christmas_tree:")
fireworks = emojize(":fireworks:")
sparkler = emojize(":sparkler:")
firecracker = emojize(":firecracker:")
sparkles = emojize(":sparkles:")
balloon = emojize(":balloon:")
party_popper = emojize(":party_popper:")
confetti_ball = emojize(":confetti_ball:")
tanabata_tree = emojize(":tanabata_tree:")
pine_decoration = emojize(":pine_decoration:")
japanese_dolls = emojize(":japanese_dolls:")
carp_streamer = emojize(":carp_streamer:")
wind_chime = emojize(":wind_chime:")
moon_viewing_ceremony = emojize(":moon_viewing_ceremony:")
red_envelope = emojize(":red_envelope:")
ribbon = emojize(":ribbon:")
wrapped_gift = emojize(":wrapped_gift:")
reminder_ribbon = emojize(":reminder_ribbon:")
admission_tickets = emojize(":admission_tickets:")
ticket = emojize(":ticket:")
