# -*- coding: utf-8
from emoji import emojize
bullseye = emojize(":bullseye:")
yo_yo = emojize(":yo_yo:")
kite = emojize(":kite:")
pool_8_ball = emojize(":pool_8_ball:")
crystal_ball = emojize(":crystal_ball:")
magic_wand = emojize(":magic_wand:")
nazar_amulet = emojize(":nazar_amulet:")
hamsa = emojize(":hamsa:")
video_game = emojize(":video_game:")
joystick = emojize(":joystick:")
slot_machine = emojize(":slot_machine:")
game_die = emojize(":game_die:")
puzzle_piece = emojize(":puzzle_piece:")
teddy_bear = emojize(":teddy_bear:")
pinata = emojize(":pinata:")
mirror_ball = emojize(":mirror_ball:")
nesting_dolls = emojize(":nesting_dolls:")
spade_suit = emojize(":spade_suit:")
heart_suit = emojize(":heart_suit:")
diamond_suit = emojize(":diamond_suit:")
club_suit = emojize(":club_suit:")
chess_pawn = emojize(":chess_pawn:")
joker = emojize(":joker:")
mahjong_red_dragon = emojize(":mahjong_red_dragon:")
flower_playing_cards = emojize(":flower_playing_cards:")
