# -*- coding: utf-8
from emoji import emojize
bullseye = emojize(":bullseye:")
yo_yo = emojize(":yo-yo:")
kite = emojize(":kite:")
pool_8_ball = emojize(":pool 8 ball:")
crystal_ball = emojize(":crystal ball:")
magic_wand = emojize(":magic wand:")
nazar_amulet = emojize(":nazar amulet:")
hamsa = emojize(":hamsa:")
video_game = emojize(":video game:")
joystick = emojize(":joystick:")
slot_machine = emojize(":slot machine:")
game_die = emojize(":game die:")
puzzle_piece = emojize(":puzzle piece:")
teddy_bear = emojize(":teddy bear:")
pinata = emojize(":piñata:")
mirror_ball = emojize(":mirror ball:")
nesting_dolls = emojize(":nesting dolls:")
spade_suit = emojize(":spade suit:")
heart_suit = emojize(":heart suit:")
diamond_suit = emojize(":diamond suit:")
club_suit = emojize(":club suit:")
chess_pawn = emojize(":chess pawn:")
joker = emojize(":joker:")
mahjong_red_dragon = emojize(":mahjong red dragon:")
flower_playing_cards = emojize(":flower playing cards:")
