# -*- coding: utf-8
from emoji import emojize
baby_bottle = emojize(":baby_bottle:")
glass_of_milk = emojize(":glass_of_milk:")
hot_beverage = emojize(":hot_beverage:")
teapot = emojize(":teapot:")
teacup_without_handle = emojize(":teacup_without_handle:")
sake = emojize(":sake:")
bottle_with_popping_cork = emojize(":bottle_with_popping_cork:")
wine_glass = emojize(":wine_glass:")
cocktail_glass = emojize(":cocktail_glass:")
tropical_drink = emojize(":tropical_drink:")
beer_mug = emojize(":beer_mug:")
clinking_beer_mugs = emojize(":clinking_beer_mugs:")
clinking_glasses = emojize(":clinking_glasses:")
tumbler_glass = emojize(":tumbler_glass:")
pouring_liquid = emojize(":pouring_liquid:")
cup_with_straw = emojize(":cup_with_straw:")
bubble_tea = emojize(":bubble_tea:")
beverage_box = emojize(":beverage_box:")
mate = emojize(":mate:")
ice = emojize(":ice:")
