# -*- coding: utf-8
from emoji import emojize
baby_bottle = emojize(":baby bottle:")
glass_of_milk = emojize(":glass of milk:")
hot_beverage = emojize(":hot beverage:")
teapot = emojize(":teapot:")
teacup_without_handle = emojize(":teacup without handle:")
sake = emojize(":sake:")
bottle_with_popping_cork = emojize(":bottle with popping cork:")
wine_glass = emojize(":wine glass:")
cocktail_glass = emojize(":cocktail glass:")
tropical_drink = emojize(":tropical drink:")
beer_mug = emojize(":beer mug:")
clinking_beer_mugs = emojize(":clinking beer mugs:")
clinking_glasses = emojize(":clinking glasses:")
tumbler_glass = emojize(":tumbler glass:")
pouring_liquid = emojize(":pouring liquid:")
cup_with_straw = emojize(":cup with straw:")
bubble_tea = emojize(":bubble tea:")
beverage_box = emojize(":beverage box:")
mate = emojize(":mate:")
ice = emojize(":ice:")
