# -*- coding: utf-8
from emoji import emojize
soft_ice_cream = emojize(":soft ice cream:")
shaved_ice = emojize(":shaved ice:")
ice_cream = emojize(":ice cream:")
doughnut = emojize(":doughnut:")
cookie = emojize(":cookie:")
birthday_cake = emojize(":birthday cake:")
shortcake = emojize(":shortcake:")
cupcake = emojize(":cupcake:")
pie = emojize(":pie:")
chocolate_bar = emojize(":chocolate bar:")
candy = emojize(":candy:")
lollipop = emojize(":lollipop:")
custard = emojize(":custard:")
honey_pot = emojize(":honey pot:")
