# -*- coding: utf-8
from emoji import emojize
grapes = emojize(":grapes:")
melon = emojize(":melon:")
watermelon = emojize(":watermelon:")
tangerine = emojize(":tangerine:")
lemon = emojize(":lemon:")
banana = emojize(":banana:")
pineapple = emojize(":pineapple:")
mango = emojize(":mango:")
red_apple = emojize(":red apple:")
green_apple = emojize(":green apple:")
pear = emojize(":pear:")
peach = emojize(":peach:")
cherries = emojize(":cherries:")
strawberry = emojize(":strawberry:")
blueberries = emojize(":blueberries:")
kiwi_fruit = emojize(":kiwi fruit:")
tomato = emojize(":tomato:")
olive = emojize(":olive:")
coconut = emojize(":coconut:")
