# -*- coding: utf-8
from emoji import emojize
bento_box = emojize(":bento_box:")
rice_cracker = emojize(":rice_cracker:")
rice_ball = emojize(":rice_ball:")
cooked_rice = emojize(":cooked_rice:")
curry_rice = emojize(":curry_rice:")
steaming_bowl = emojize(":steaming_bowl:")
spaghetti = emojize(":spaghetti:")
roasted_sweet_potato = emojize(":roasted_sweet_potato:")
oden = emojize(":oden:")
sushi = emojize(":sushi:")
fried_shrimp = emojize(":fried_shrimp:")
fish_cake_with_swirl = emojize(":fish_cake_with_swirl:")
moon_cake = emojize(":moon_cake:")
dango = emojize(":dango:")
dumpling = emojize(":dumpling:")
fortune_cookie = emojize(":fortune_cookie:")
takeout_box = emojize(":takeout_box:")
