# -*- coding: utf-8
from emoji import emojize
avocado = emojize(":avocado:")
eggplant = emojize(":eggplant:")
potato = emojize(":potato:")
carrot = emojize(":carrot:")
ear_of_corn = emojize(":ear of corn:")
hot_pepper = emojize(":hot pepper:")
bell_pepper = emojize(":bell pepper:")
cucumber = emojize(":cucumber:")
leafy_green = emojize(":leafy green:")
broccoli = emojize(":broccoli:")
garlic = emojize(":garlic:")
onion = emojize(":onion:")
mushroom = emojize(":mushroom:")
peanuts = emojize(":peanuts:")
beans = emojize(":beans:")
chestnut = emojize(":chestnut:")
