# -*- coding: utf-8
from emoji import emojize
bento_box = emojize(":bento box:")
rice_cracker = emojize(":rice cracker:")
rice_ball = emojize(":rice ball:")
cooked_rice = emojize(":cooked rice:")
curry_rice = emojize(":curry rice:")
steaming_bowl = emojize(":steaming bowl:")
spaghetti = emojize(":spaghetti:")
roasted_sweet_potato = emojize(":roasted sweet potato:")
oden = emojize(":oden:")
sushi = emojize(":sushi:")
fried_shrimp = emojize(":fried shrimp:")
fish_cake_with_swirl = emojize(":fish cake with swirl:")
moon_cake = emojize(":moon cake:")
dango = emojize(":dango:")
dumpling = emojize(":dumpling:")
fortune_cookie = emojize(":fortune cookie:")
takeout_box = emojize(":takeout box:")
