# -*- coding: utf-8
from emoji import emojize
fountain = emojize(":fountain:")
tent = emojize(":tent:")
foggy = emojize(":foggy:")
night_with_stars = emojize(":night with stars:")
cityscape = emojize(":cityscape:")
sunrise_over_mountains = emojize(":sunrise over mountains:")
sunrise = emojize(":sunrise:")
cityscape_at_dusk = emojize(":cityscape at dusk:")
sunset = emojize(":sunset:")
bridge_at_night = emojize(":bridge at night:")
hot_springs = emojize(":hot springs:")
carousel_horse = emojize(":carousel horse:")
playground_slide = emojize(":playground slide:")
ferris_wheel = emojize(":ferris wheel:")
roller_coaster = emojize(":roller coaster:")
barber_pole = emojize(":barber pole:")
circus_tent = emojize(":circus tent:")
