# -*- coding: utf-8
from emoji import emojize
airplane = emojize(":airplane:")
small_airplane = emojize(":small airplane:")
airplane_departure = emojize(":airplane departure:")
airplane_arrival = emojize(":airplane arrival:")
parachute = emojize(":parachute:")
seat = emojize(":seat:")
helicopter = emojize(":helicopter:")
suspension_railway = emojize(":suspension railway:")
mountain_cableway = emojize(":mountain cableway:")
aerial_tramway = emojize(":aerial tramway:")
satellite = emojize(":satellite:")
rocket = emojize(":rocket:")
flying_saucer = emojize(":flying saucer:")
