# -*- coding: utf-8
from emoji import emojize
writing_hand = emojize(":writing_hand:")
writing_hand_light_skin_tone = emojize(":light_skin_tone:")
writing_hand_medium_light_skin_tone = emojize(":medium_light_skin_tone:")
writing_hand_medium_skin_tone = emojize(":medium_skin_tone:")
writing_hand_medium_dark_skin_tone = emojize(":medium_dark_skin_tone:")
writing_hand_dark_skin_tone = emojize(":dark_skin_tone:")
nail_polish = emojize(":nail_polish:")
nail_polish_light_skin_tone = emojize(":light_skin_tone:")
nail_polish_medium_light_skin_tone = emojize(":medium_light_skin_tone:")
nail_polish_medium_skin_tone = emojize(":medium_skin_tone:")
nail_polish_medium_dark_skin_tone = emojize(":medium_dark_skin_tone:")
nail_polish_dark_skin_tone = emojize(":dark_skin_tone:")
selfie = emojize(":selfie:")
selfie_light_skin_tone = emojize(":light_skin_tone:")
selfie_medium_light_skin_tone = emojize(":medium_light_skin_tone:")
selfie_medium_skin_tone = emojize(":medium_skin_tone:")
selfie_medium_dark_skin_tone = emojize(":medium_dark_skin_tone:")
selfie_dark_skin_tone = emojize(":dark_skin_tone:")
