# -*- coding: utf-8
from emoji import emojize
writing_hand = emojize(":writing hand:")
writing_hand_light_skin_tone = emojize(":light skin tone:")
writing_hand_medium_light_skin_tone = emojize(":medium-light skin tone:")
writing_hand_medium_skin_tone = emojize(":medium skin tone:")
writing_hand_medium_dark_skin_tone = emojize(":medium-dark skin tone:")
writing_hand_dark_skin_tone = emojize(":dark skin tone:")
nail_polish = emojize(":nail polish:")
nail_polish_light_skin_tone = emojize(":light skin tone:")
nail_polish_medium_light_skin_tone = emojize(":medium-light skin tone:")
nail_polish_medium_skin_tone = emojize(":medium skin tone:")
nail_polish_medium_dark_skin_tone = emojize(":medium-dark skin tone:")
nail_polish_dark_skin_tone = emojize(":dark skin tone:")
selfie = emojize(":selfie:")
selfie_light_skin_tone = emojize(":light skin tone:")
selfie_medium_light_skin_tone = emojize(":medium-light skin tone:")
selfie_medium_skin_tone = emojize(":medium skin tone:")
selfie_medium_dark_skin_tone = emojize(":medium-dark skin tone:")
selfie_dark_skin_tone = emojize(":dark skin tone:")
