# -*- coding: utf-8
from emoji import emojize
fountain = emojize(":fountain:")
tent = emojize(":tent:")
foggy = emojize(":foggy:")
night_with_stars = emojize(":night_with_stars:")
cityscape = emojize(":cityscape:")
sunrise_over_mountains = emojize(":sunrise_over_mountains:")
sunrise = emojize(":sunrise:")
cityscape_at_dusk = emojize(":cityscape_at_dusk:")
sunset = emojize(":sunset:")
bridge_at_night = emojize(":bridge_at_night:")
hot_springs = emojize(":hot_springs:")
carousel_horse = emojize(":carousel_horse:")
playground_slide = emojize(":playground_slide:")
ferris_wheel = emojize(":ferris_wheel:")
roller_coaster = emojize(":roller_coaster:")
barber_pole = emojize(":barber_pole:")
circus_tent = emojize(":circus_tent:")
