# -*- coding: utf-8
from emoji import emojize
chequered_flag = emojize(":chequered flag:")
triangular_flag = emojize(":triangular flag:")
crossed_flags = emojize(":crossed flags:")
black_flag = emojize(":black flag:")
white_flag = emojize(":white flag:")
rainbow_flag = emojize(":rainbow flag:")
transgender_flag = emojize(":transgender flag:")
pirate_flag = emojize(":pirate flag:")
