# -*- coding: utf-8
from emoji import emojize
up_arrow = emojize(":up_arrow:")
up_right_arrow = emojize(":up-right_arrow:")
right_arrow = emojize(":right_arrow:")
down_right_arrow = emojize(":down-right_arrow:")
down_arrow = emojize(":down_arrow:")
down_left_arrow = emojize(":down-left_arrow:")
left_arrow = emojize(":left_arrow:")
up_left_arrow = emojize(":up-left_arrow:")
up_down_arrow = emojize(":up-down_arrow:")
left_right_arrow = emojize(":left-right_arrow:")
right_arrow_curving_left = emojize(":right_arrow_curving_left:")
left_arrow_curving_right = emojize(":left_arrow_curving_right:")
right_arrow_curving_up = emojize(":right_arrow_curving_up:")
right_arrow_curving_down = emojize(":right_arrow_curving_down:")
clockwise_vertical_arrows = emojize(":clockwise_vertical_arrows:")
counterclockwise_arrows_button = emojize(":counterclockwise_arrows_button:")
back_arrow = emojize(":BACK_arrow:")
end_arrow = emojize(":END_arrow:")
on_arrow = emojize(":ON!_arrow:")
soon_arrow = emojize(":SOON_arrow:")
top_arrow = emojize(":TOP_arrow:")
