# -*- coding: utf-8
from emoji import emojize
shuffle_tracks_button = emojize(":shuffle_tracks_button:")
repeat_button = emojize(":repeat_button:")
repeat_single_button = emojize(":repeat_single_button:")
play_button = emojize(":play_button:")
fast_forward_button = emojize(":fast-forward_button:")
next_track_button = emojize(":next_track_button:")
play_or_pause_button = emojize(":play_or_pause_button:")
reverse_button = emojize(":reverse_button:")
fast_reverse_button = emojize(":fast_reverse_button:")
last_track_button = emojize(":last_track_button:")
upwards_button = emojize(":upwards_button:")
fast_up_button = emojize(":fast_up_button:")
downwards_button = emojize(":downwards_button:")
fast_down_button = emojize(":fast_down_button:")
pause_button = emojize(":pause_button:")
stop_button = emojize(":stop_button:")
record_button = emojize(":record_button:")
eject_button = emojize(":eject_button:")
cinema = emojize(":cinema:")
dim_button = emojize(":dim_button:")
bright_button = emojize(":bright_button:")
antenna_bars = emojize(":antenna_bars:")
vibration_mode = emojize(":vibration_mode:")
mobile_phone_off = emojize(":mobile_phone_off:")
