# -*- coding: utf-8
from emoji import emojize
medical_symbol = emojize(":medical_symbol:")
recycling_symbol = emojize(":recycling_symbol:")
fleur_de_lis = emojize(":fleur-de-lis:")
trident_emblem = emojize(":trident_emblem:")
name_badge = emojize(":name_badge:")
japanese_symbol_for_beginner = emojize(":Japanese_symbol_for_beginner:")
hollow_red_circle = emojize(":hollow_red_circle:")
check_mark_button = emojize(":check_mark_button:")
check_box_with_check = emojize(":check_box_with_check:")
check_mark = emojize(":check_mark:")
cross_mark = emojize(":cross_mark:")
cross_mark_button = emojize(":cross_mark_button:")
curly_loop = emojize(":curly_loop:")
double_curly_loop = emojize(":double_curly_loop:")
part_alternation_mark = emojize(":part_alternation_mark:")
eight_spoked_asterisk = emojize(":eight-spoked_asterisk:")
eight_pointed_star = emojize(":eight-pointed_star:")
sparkle = emojize(":sparkle:")
copyright = emojize(":copyright:")
registered = emojize(":registered:")
trade_mark = emojize(":trade_mark:")
