# -*- coding: utf-8
from emoji import emojize
warning = emojize(":warning:")
children_crossing = emojize(":children_crossing:")
no_entry = emojize(":no_entry:")
prohibited = emojize(":prohibited:")
no_bicycles = emojize(":no_bicycles:")
no_smoking = emojize(":no_smoking:")
no_littering = emojize(":no_littering:")
non_potable_water = emojize(":non-potable_water:")
no_pedestrians = emojize(":no_pedestrians:")
no_mobile_phones = emojize(":no_mobile_phones:")
no_one_under_eighteen = emojize(":no_one_under_eighteen:")
radioactive = emojize(":radioactive:")
biohazard = emojize(":biohazard:")
