# -*- coding: utf-8
from emoji import emojize
zipper_mouth_face = emojize(":zipper-mouth face:")
face_with_raised_eyebrow = emojize(":face with raised eyebrow:")
neutral_face = emojize(":neutral face:")
expressionless_face = emojize(":expressionless face:")
face_without_mouth = emojize(":face without mouth:")
dotted_line_face = emojize(":dotted line face:")
face_in_clouds = emojize(":face in clouds:")
smirking_face = emojize(":smirking face:")
unamused_face = emojize(":unamused face:")
face_with_rolling_eyes = emojize(":face with rolling eyes:")
grimacing_face = emojize(":grimacing face:")
face_exhaling = emojize(":face exhaling:")
lying_face = emojize(":lying face:")
