# -*- coding: utf-8
from emoji import emojize
grinning_face = emojize(":grinning face:")
grinning_face_with_big_eyes = emojize(":grinning face with big eyes:")
grinning_face_with_smiling_eyes = emojize(":grinning face with smiling eyes:")
beaming_face_with_smiling_eyes = emojize(":beaming face with smiling eyes:")
grinning_squinting_face = emojize(":grinning squinting face:")
grinning_face_with_sweat = emojize(":grinning face with sweat:")
rolling_on_the_floor_laughing = emojize(":rolling on the floor laughing:")
face_with_tears_of_joy = emojize(":face with tears of joy:")
slightly_smiling_face = emojize(":slightly smiling face:")
upside_down_face = emojize(":upside-down face:")
melting_face = emojize(":melting face:")
winking_face = emojize(":winking face:")
smiling_face_with_smiling_eyes = emojize(":smiling face with smiling eyes:")
smiling_face_with_halo = emojize(":smiling face with halo:")
