# -*- coding: utf-8
from emoji import emojize
confused_face = emojize(":confused face:")
face_with_diagonal_mouth = emojize(":face with diagonal mouth:")
worried_face = emojize(":worried face:")
slightly_frowning_face = emojize(":slightly frowning face:")
frowning_face = emojize(":frowning face:")
face_with_open_mouth = emojize(":face with open mouth:")
hushed_face = emojize(":hushed face:")
astonished_face = emojize(":astonished face:")
flushed_face = emojize(":flushed face:")
pleading_face = emojize(":pleading face:")
face_holding_back_tears = emojize(":face holding back tears:")
frowning_face_with_open_mouth = emojize(":frowning face with open mouth:")
anguished_face = emojize(":anguished face:")
fearful_face = emojize(":fearful face:")
anxious_face_with_sweat = emojize(":anxious face with sweat:")
sad_but_relieved_face = emojize(":sad but relieved face:")
crying_face = emojize(":crying face:")
loudly_crying_face = emojize(":loudly crying face:")
face_screaming_in_fear = emojize(":face screaming in fear:")
confounded_face = emojize(":confounded face:")
persevering_face = emojize(":persevering face:")
disappointed_face = emojize(":disappointed face:")
downcast_face_with_sweat = emojize(":downcast face with sweat:")
weary_face = emojize(":weary face:")
tired_face = emojize(":tired face:")
yawning_face = emojize(":yawning face:")
