# -*- coding: utf-8
from emoji import emojize
confused_face = emojize(":confused_face:")
face_with_diagonal_mouth = emojize(":face_with_diagonal_mouth:")
worried_face = emojize(":worried_face:")
slightly_frowning_face = emojize(":slightly_frowning_face:")
frowning_face = emojize(":frowning_face:")
face_with_open_mouth = emojize(":face_with_open_mouth:")
hushed_face = emojize(":hushed_face:")
astonished_face = emojize(":astonished_face:")
flushed_face = emojize(":flushed_face:")
pleading_face = emojize(":pleading_face:")
face_holding_back_tears = emojize(":face_holding_back_tears:")
frowning_face_with_open_mouth = emojize(":frowning_face_with_open_mouth:")
anguished_face = emojize(":anguished_face:")
fearful_face = emojize(":fearful_face:")
anxious_face_with_sweat = emojize(":anxious_face_with_sweat:")
sad_but_relieved_face = emojize(":sad_but_relieved_face:")
crying_face = emojize(":crying_face:")
loudly_crying_face = emojize(":loudly_crying_face:")
face_screaming_in_fear = emojize(":face_screaming_in_fear:")
confounded_face = emojize(":confounded_face:")
persevering_face = emojize(":persevering_face:")
disappointed_face = emojize(":disappointed_face:")
downcast_face_with_sweat = emojize(":downcast_face_with_sweat:")
weary_face = emojize(":weary_face:")
tired_face = emojize(":tired_face:")
yawning_face = emojize(":yawning_face:")
